baseurl         = "https://blog.chriscoffee.com/"
theme           = "chris-blog"
languageCode    = "en-US"
disqusShortname = "chriscoffee"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Chris' Coffee"
  subtitle    = "Experts in Coffee Since 1975"
  cover       = "img/cc-blog_header.jpg"
  description = "Experts in coffee since 1975, Chris' Coffee strives to share our industry knowledge and answer all question our customers have. Subscribe to our blog for the latest knowledge added weeekly."
  metaDescription = ""
  googleAnalytics = "UA-1513659-2"
  customCSS = []
  RSSLink = "/index.xml"

  twitterName = "chriscoffeeserv"
  fbName = "chriscoffeeservice"
  instaName = "chriscoffeeservice"
  inName = "chriscoffeeservice"

  logo = "chris-coffee-logo-vertical.svg"
  smlogo = "home.svg"
  orgName = "Chris' Coffee Service"
  orgWebsite = "https://www.chriscoffee.com/"
  orgDescription = "Spcializing in the best home and commercial espresso machines and roasting over 100k pounds a month we know coffee. Join us in our journey finding the best home and commercial coffee equipment from top brands like La Spaziale, Slayer, Rancilio, La Cimbali, La Marzocco, and many more."

  author = "Chris"
  authorAvatar = "img/chris-icon.jpg"
  authorLocation = "Albany, NY"
  authorWebsite = "https://www.chriscoffee.com/"
  authorDescription = "Starting out of the back of an El Camino with the help of my family and a couple off duty cops, Chris' Coffee Service has been the experts in coffee since 1975."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Shop"
  url = "https://www.chriscoffee.com/"
  weight = 200

[[menu.main]]
  name = "Reviews"
  url = "/categories/reviews/"
  weight = 100

[[menu.main]]
  name = "How-To"
  url = "/categories/how-to"
  weight = 98

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 95
